version: "2"
services:
    python_code:
        build:
            context: .
            dockerfile: dockerfile-api
        ports:
            - 5000:5000
        networks: 
            - front-tier
            - back-tier
        links:
            - db_blend

    db_blend:
        container_name: "api_db_blend"
        build:
            context: .
            dockerfile: dockerfile-mysql
        ports:
            - 6000:3306
        networks:
            - back-tier
        env_file: mysql_env
        volumes:    
            - /storage/docker/mysql-datadir:/var/lib/mysql

    lb:
        image: dockercloud/haproxy
        ports:
            - 8080:80
        networks: 
            - front-tier
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock 
        links:
            - python_code

networks:
    front-tier: 
        driver: bridge
    back-tier:
        driver: bridge



